<!-- ======= Styles ====== -->
<link rel="stylesheet" href="assets/css/style.css">
<link rel="stylesheet" href="assets/css/styleButtonAjouter.css">

<style>
    /* Button update et supprimer */
    .ButtonsUpSupp a {
        text-decoration: none;
        padding: 10px 15px;
        border-radius: 5px;
        display: inline-flex;
        align-items: center;
        font-weight: bold;
        transition: background-color 0.3s ease, transform 0.3s ease;
    }

    /* Bouton Update (jaune) */
    .btn-update {
        background-color: #f1c40f;
        color: #fff;
    }

    .btn-update:hover {
        background-color: #f39c12;
        transform: scale(1.05);
    }

    /* Bouton Delete (rouge) */
    .btn-delete {
        background-color: #e74c3c;
        color: #fff;
    }

    .btn-delete:hover {
        background-color: #c0392b;
        transform: scale(1.05);
    }

    /* Style pour les icônes */
    a i {
        margin-right: 5px;
    }
</style>

        <!-- ================ Order Details List ================= -->
        <div class="details">
            <div class="recentOrders" style="min-height: 200px;">
                <div class="cardHeader">
                    <h2>Liste des feedback</h2>
                </div>
                <!-- ================ LES TABLEAUX ICI ================= -->
                <table>
                    <thead>
                        <tr>
                            <td>Username</td>
                            <td>Commentaire</td>
                            <td>Id Adherent</td>
                        </tr>
                    </thead>
                    <tbody id="contenu">
                        <?php foreach ($feedbacks as $feedback): ?>
                            <tr>
                                <td><?= $feedback['username'] ?></td>
                                <td><?= $feedback['commentaire'] ?></td>
                                <td><?= $feedback['id_ad'] ?></td>

                                <td>
                                    <div class="ButtonsUpSupp">
                                        <a href="DeleteFeedback.php?id=<?= $feedback['id'] ?>" class="btn-delete"><i class="fa-solid fa-trash"></i></a>
                                    </div>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>

            </div>

        </div>



